services:
  web:
    image: cornellappdev/big-red-bot:${SLACK_BOT_IMG_TAG}
    env_file: .env
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - ./service_account.json:/usr/app/service_account.json 
    restart: on-failure
